AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
using AQS_Application.Dtos.BaseServiceDto.Company;
using AQS_Application.Interfaces.IServices.BaseServices;
using AQS_Application.Interfaces.IServices.IdentityServices;
using AQS_Common.Enums;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebSite.EndPoint.Areas.Company.Models.Company;
using WebSite.EndPoint.Areas.Company.Models.Profile;
using WebSite.EndPoint.Utility;
using static AQS_Common.Enums.FolderNamesEnum;

namespace WebSite.EndPoint.Areas.Company.Controllers
{
    [Area("Company")]
    [Authorize(Roles = "Admin,Company")]
    public class CompanyProfileController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IRegistrationService _registrationService;
        private readonly ILoginService _loginService;
        private readonly IFileServices _fileServices;
        private readonly IVideoService _videoService;

        static string PictureFolder = FolderNamesEnum.GetFileName(FolderTypes.CompanyProfile);
        static string TeaserFoldr = FolderNamesEnum.GetFileName(FolderTypes.CompanyTeaser);
        public CompanyProfileController(
            ICompanyService companyService,
            IRegistrationService registrationService,
            ILoginService loginService,
            IFileServices fileServices,
            IVideoService videoService)
        {
            _companyService = companyService;
            _registrationService = registrationService;
            _loginService = loginService;
            _fileServices = fileServices;
            _videoService = videoService;
        }
        public Task<IActionResult> ChangePassword()
        {
            var model = new PasswordEditVm();
            return Task.FromResult<IActionResult>(View(model));
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(PasswordEditVm model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.CurrentPassword == model.NewPassword)
            {
                ViewData["error"] = "گذرواژه فعلی و رمز عبور جدید نمی‌توانند یکسان باشند";
                return View(model);
            }

            long companyId = 0;
            if (User.Identity.IsAuthenticated)
            {
                companyId = await _loginService.GetUserIdAsync(User);
            }
            else /*if (companyId < 1)*/
            {
                ViewData["error"] = "شما نیاز به ورود مجدد دارید. مدت زمان شما به پایان رسیده است.";
                return View(model);
            }
            var checkPassword = await _loginService.IsValidPassword(companyId, model.CurrentPassword);
            if (!checkPassword)
            {
                ViewData["error"] = "گذرواژه فعلی صحیح نیست";
                return View(model);
            }
            var result = await _registrationService
                .ChangePasswordAsync(companyId, model.CurrentPassword, model.NewPassword);

            if (result.userId == 0)
            {
                ViewData["error"] = result.errorMessage;
                return View(model);
            }
            else
            {
                await _loginService.LogoutAsync();
                return Redirect("/login/login");
            }
        }
        public async Task<IActionResult> EditCompanyProfile()
        {
            if (TempData["SendRequestToAdmin"] is not null)
                ViewData["error"] = TempData["SendRequestToAdmin"];

            CompanyEditProfileVM model = await EditProfileModelCreator();

            return View(model);
        }

        private async Task<CompanyEditProfileVM> EditProfileModelCreator()
        {
            long companyId = await _loginService.GetUserIdAsync(User);

            var company = await _companyService.ReadByIdAsync(companyId);
            if (company == null)
            {
                ViewData["error"] = "کاربر یافت نشد";
                return new CompanyEditProfileVM();
            }
            var model = new CompanyEditProfileVM

            {
                Id = companyId,
                Name = company.Name,
                ManagerName = company.ManagerName,
                MobileNumber = company.MobileNumber,
                Email = company.Email,
                Address = company.Address,
                Brands = company.Brands,
                Capacity = company.Capacity,
                Partnership = company.Partnership,
                QualityGrade = company.QualityGrade,
                Iso = company.Iso,
                About = company.About,
                LogoRout = company.LogoRout == null ? string.Empty : company.LogoRout,
                SendRequest = company.SendRequest,
                IsCompany = company.IsCompany,
                Tel = company.Tel,
                Website = company.Website
            };
            return model;
        }

        [HttpPost]
        public async Task<IActionResult> EditCompanyProfile(CompanyEditProfileVM companyEditProfileVM) //ToDo
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(nameof(EditCompanyProfile), companyEditProfileVM);
                }
                if (companyEditProfileVM.IsLogoChanged)
                {
                    if( await DeletePicture(companyEditProfileVM.LogoRout))
                        companyEditProfileVM.LogoRout = null;

                    if (companyEditProfileVM.Logo != null)
                    {
                       string newLogo  = await AddPicture(companyEditProfileVM.Logo);
                       if (string.IsNullOrEmpty(newLogo))
                       {
                           ViewData["error"] = "خطایی در هنگام دخیره لوگو رخ داد";
                           return View(nameof(EditCompanyProfile),companyEditProfileVM);
                       }
                       companyEditProfileVM.LogoRout = newLogo;
                    }
                }

                var dto = companyEditProfileVM.MapToDto(companyEditProfileVM);

                var resultMessage = await _companyService.UpdateEditProfile(dto);
                ViewData["error"] = resultMessage == ResultOutPutMethodEnum.savechanged ? "مشخصات ویرایش شد" :
                                    resultMessage == ResultOutPutMethodEnum.recordNotFounded ? "کاربر یافت نشد" :
                                    "مشخطات ویرایش نشد";

                if (ResultOutPutMethodEnum.savechanged == resultMessage)
                {
                    return Redirect("/Company/CompanyPanel/Panel");
                }

                return View(companyEditProfileVM);
            }
            catch (Exception ex)
            {
                ViewData["error"] = ex.Message;
                return View(companyEditProfileVM);
            }
        }
        private async Task<bool> DeletePicture(string route)
        {
            return await _fileServices.DeleteFile(route);
        }
        private async Task<string> AddPicture(IFormFile newPicture)
        {
            return  await _fileServices.SaveFileAsync(newPicture, PictureFolder);
        }
        public async Task<IActionResult> SendRequestToAdmin(long id, bool sendRequest)
        {
            var resultMessage = await _companyService.SendRequest(id, sendRequest);

            TempData["SendRequestToAdmin"] =
                                resultMessage == ResultOutPutMethodEnum.savechanged ? "درخواست ارسال شد" :
                                resultMessage == ResultOutPutMethodEnum.recordNotFounded ? "مشخصات کاربری یافت نشد." :
                                resultMessage == ResultOutPutMethodEnum.duplicateRecord ? "شما قبلا درخواست داده اید"
                                : "ارسال درخواست با مشکل مواجه شد";

            return RedirectToAction(nameof(EditCompanyProfile));
        }

        
        public async Task<IActionResult> EditTeaser(string msg = "")
        {
            if (!string.IsNullOrEmpty(msg))
            {
                ViewData["msg"] = msg;
            }

            long companyId = await _loginService.GetUserIdAsync(User);
            var company = await _companyService.ReadByIdAsync(companyId);
            if (company != null)
                ViewData["src"] = company.TeaserGuid;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditTeaser(IFormFile teaser)
        {
            if (teaser == null)
                return RedirectToAction(nameof(EditTeaser));

            long companyId = await _loginService.GetUserIdAsync(User);

            string msg = string.Empty;
            var company = await _companyService.ReadByIdAsync(companyId);
            if (company != null)
            {
                string teaserPath = await _videoService.SaveVideoAsync(teaser, TeaserFoldr);
                if (string.IsNullOrEmpty(teaserPath))
                {
                    msg = "خطا در هنگام ذخیره ویدیو";
                }
                company.TeaserGuid = teaserPath;
                var result = await _companyService.UpdateTeaser(company);
                if (result == ResultOutPutMethodEnum.savechanged)
                    msg = "تغییرات با موفقیت ذخیره شد";
                else
                    msg = "خطا در هنگام ذخیره اطلاعات ";
            }
            return RedirectToAction(nameof(EditTeaser), new { msg = msg });
        }
        public async Task<IActionResult> DeleteTeaser()//OK
        {

            long companyId = await _loginService.GetUserIdAsync(User);
            string msg = string.Empty;
            var company = await _companyService.ReadByIdAsync(companyId);
            if (company != null && !string.IsNullOrEmpty(company.TeaserGuid))
            {
                if (await _videoService.DeleteVideo(company.TeaserGuid))
                {
                    company.TeaserGuid = string.Empty;

AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/ChangePassword.cshtml
@model WebSite.EndPoint.Areas.Company.Models.Profile.PasswordEditVm
@{
    Layout = "~/Areas/Company/Views/Shared/_layout.cshtml";
    ViewData["SelectedCompany"] = "ChangePassword";
}
<div class="container-fluid">
    <div class="pageName">
        <span class="textPage">تغییر رمز عبور</span>
    </div>
    @if (ViewData["error"] is not null)
    {
        <div id="viewDataErrorContainer" class="row pageMargin">
            <p class="text-danger border-5">@ViewData["error"].ToString()</p>
        </div>

    }

    @* <div>
        <a href="#" id="save"><img class="img-Icon" src="~/images/diskette copy.png" /></a>
    </div> *@
    <div class="pageMargin">
        <form id="saveForm" asp-area="Company" asp-controller="CompanyProfile" asp-action="ChangePassword" method="post">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label input-Label">رمز عبور فعلی</label>
                <div class="col-sm-4">
                    <input type="password" asp-for="CurrentPassword"  class="input-text">
                    <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label input-Label">رمز عبور جدید</label>
                <div class="col-sm-4">
                    <input type="password" asp-for="NewPassword" class="input-text">
                    <span class="changePassHelp">رمز عبور باید حداقل 6 کارکتر باشد</span>
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label input-Label">تکرار رمز عبور جدید</label>
                <div class="col-sm-4">
                    <input type="password" asp-for = "ComparePassword" class="input-text">
                    <span asp-validation-for="ComparePassword" class="text-danger"></span>
                </div>
            </div>
            <div>
                <div class="row mt-2 pageMargin">
                    <div class="col-md-5 my-2">
                        <a href="#" id="save" class="text-black btn-submit btn-block a-btn">
                            <span class="text-btn">ذخیره</span>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    <script>
        $("#save").click(function(event){
            event.preventDefault();
            $("#saveForm").submit();
        });
        setTimeout(function() {
                var errorMsg = document.getElementById("viewDataErrorContainer");
                if (errorMsg) {
                    errorMsg.style.display = "none";
                }
            }, 5000);  // 5000 میلی‌ثانیه = 5 ثانیه
    </script>
}

AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
@model WebSite.EndPoint.Areas.Company.Models.Company.CompanyEditProfileVM
@{
    Layout = "~/Areas/Company/Views/Shared/_layout.cshtml";
    ViewData["SelectedCompany"] = "Profile";
}

<div class="container-fluid">

    <div class="pageName">
        <span class="textPage">پروفایل کاربری</span>
    </div>
    @if (ViewData["error"] is not null)
    {
        <div id="viewDataErrorContainer" class="pageMargin">
            <p class="error-text">@ViewData["error"]?.ToString()</p>
        </div>
    }

    @* <div>
        <a href="#" id="save"><img class="img-Icon" src="~/images/diskette copy.png" /></a>
    </div> *@
    <div class="mt-2 pageMargin">
        <form enctype="multipart/form-data" id="saveForm" asp-area="Company" asp-action="EditCompanyProfile" asp-controller="CompanyProfile" method="post">
            <input asp-for="Id" type="hidden" />
            <input type="hidden" asp-for="LogoRout" />
            <input hidden asp-for="IsCompany" />
            <div class="row">
                <div class="col-md-6 userEditRow">
                    <label for="Cname" class="labelText">نام شرکت</label>
                    <input asp-for="Name" class="labelText input-text" type="text" id="Cname" />
                    <span class="text-danger" asp-validation-for=Name></span>
                </div>
                <div class="col-md-6 userEditRow">
                    <label for="CFoundername" class="labelText">نام مدیر عامل</label>
                    <input asp-for="ManagerName" class="labelText input-text" type="text" id="CFoundername" />
                    <span class="text-danger" asp-validation-for=ManagerName></span>
                </div>
                <div class="col-md-6 userEditRow">
                    <label for="CMobile" class="labelText">شماره موبایل</label>
                    <input asp-for="MobileNumber"
                           class="labelText input-text"
                           oninput="this.value=this.value.replace(/(?![0-9])./gmi,'')"
                           type="text"
                           id="CMobile" />
                    <span class="text-danger" asp-validation-for=MobileNumber></span>
                </div>
                <div class="col-md-6 userEditRow">
                    <label for="CEmail" class="labelText">ایمیل</label>
                    <input asp-for="Email" class="labelText input-text" type="text" id="CEmail" />
                    <span class="text-danger" asp-validation-for=Email></span>
                </div>
                <div class="col-md-6 userEditRow">
                    <label for="CTel" class="labelText">تلفن</label>
                    <input asp-for="Tel"
                           class="labelText input-text"
                           oninput="this.value=this.value.replace(/(?![0-9])./gmi,'')"
                           type="text" id="CTel" />
                </div>
                <div class="col-md-6 userEditRow">
                    <label for="CFoundername" class="labelText">وبسایت</label>
                    <input asp-for="Website" id="CWebsite" class="labelText input-text" type="text" />
                </div>
                <div class="col-md-6 userEditRow">
                    <label for="CAddress" class="labelText">آدرس</label>
                    <textarea asp-for="Address" id="CAddress" class="input-text"></textarea>
                    <span class="text-danger" asp-validation-for=Address></span>
                </div>
                @if (Model.IsCompany)
                {
                    <div class="col-md-6 userEditRow">
                        <label for="CBrands" class="labelText">برندهای زیر مجموعه</label>
                        <textarea asp-for="Brands" id="CBrands" class="input-text"></textarea>
                    </div>
                    <div class="col-md-6 userEditRow">
                        <label for="CCollab" class="labelText">همکاری با شرکت‌های</label>
                        <textarea asp-for="Partnership" id="CCollab" class="input-text"></textarea>
                    </div>
                    <div class="col-md-6 userEditRow">
                        <label for="CCapacity" class="labelText">ظرفیت تولید</label>
                        <textarea asp-for="Capacity" id="CCapacity" class="input-text"></textarea>
                    </div>
                    <div class="col-md-6 userEditRow">
                        <label for="CGrade" class="labelText">گرید کیفی</label>
                        <textarea asp-for="QualityGrade" id="CGrade" class="input-text"></textarea>
                    </div>
                    <div class="col-md-6 userEditRow">
                        <label for="CIso" class="labelText">استاندارد و ایزوهای اجباری و تشویقی</label>
                        <textarea asp-for="Iso" id="CIso" class="input-text"></textarea>
                    </div>
                    <div class="col-md-12 userEditRow">
                        <label for="CAbout" class="labelText">درباره شرکت</label>
                        <textarea asp-for="About" id="CAbout" class="input-text"></textarea>
                    </div>
                }
            </div>

            <div class="row mt-2 userEditRow">

                <div class="row pageMargin">
                    <div class="col-sm-4 col-sm-offset-5 btnAddTBPack">
                        <div class="btnAddTBPack2">
                            <div id="previewLogo" class=" ShowPicProduct">
                                @if (Model != null && !string.IsNullOrEmpty(Model.LogoRout))
                                {
                                    <img class="prevImage" src="@Model.LogoRout" />
                                }
                            </div>
                            <div class="upBtnProduct uploadDiv">
                                <button type="button" class="btn-submit btnUpload" onclick="getfileLogo()">بارگذاری لوگو</button>
                                <input asp-for="Logo" id="getFileLogo" class="form-control-file notDisplay" type="file" accept="image/*">
                            </div>
                        </div>
                        <a href="#" id="deleteLogo"><img class="img-Icon" src="~/images/recycle.png" /></a>

                    </div>

                    <input id="IsLogoChanged" type="hidden" asp-for="IsLogoChanged" />

                </div>
            </div>
        </form>
    </div>
    <div>
        <div class="row mt-2">
            <div class="col-md-5 my-2">
                <a href="#" id="save" class="text-black btn-submit btn-block a-btn">
                    <span class="text-btn">ذخیره</span>
                </a>
            </div>
        </div>
    </div>
    <div>
        @if (Model.SendRequest == false)
        {
            <div class="row mt-2 pageMargin">
                <div class="col-md-5 my-2">
                    <a href="@Url.Action("SendRequestToAdmin","CompanyProfile",new{area="Company" , id = Model.Id , sendRequest = true})" class="text-black btn-submit btn-block input-text a-btn-center">
                        <span class="text-btn">ارسال درخواست جهت شناسایی به عنوان تولید کننده</span>
                    </a>
                </div>
            </div>
        }

    </div>
</div>

@section Scripts
{
    <script>

        function getfileLogo()
        {
            document.querySelector('#getFileLogo').click();
        }

        $("#getFileLogo").on('change',function(){
            const file = this.files[0];

            if (file)
            {
                const reader = new FileReader();
                reader.onload = function (e) {
                    // ایجاد یا جایگزینی تصویر در باکس
                    const img = $("<img>")
                    .attr("src", e.target.result)
                    .addClass("img")
                    .addClass("prevImage");

                    $("#previewLogo").empty().append(img);
                };
                reader.readAsDataURL(file);

                $("#IsLogoChanged").val(true);

            } else {
                $("#previewLogo").html("پیش‌نمایش");
            }
        });


        $("#save").click(function(event){
            event.preventDefault();
            $("#saveForm").submit();
        });

        $("#deleteLogo").click(function(event) {
            event.preventDefault();
            $("#previewLogo").html("");
            $("#getFileLogo").val("");
            $("#IsLogoChanged").val(true); // changed - deleted
        });

         setTimeout(function() {
                var errorMsg = document.getElementById("viewDataErrorContainer");
                if (errorMsg) {
                    errorMsg.style.display = "none";
                }
            }, 5000);  // 5000 میلی‌ثانیه = 5 ثانیه

    </script>
}

AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditTeaser.cshtml
@{
    Layout = "~/Areas/Company/Views/Shared/_layout.cshtml";
    ViewData["SelectedCompany"] = "Teaser";
}

<div class="contaienr">
    <div class="pageName">
        <span class="textPage">تیزر تبلیغاتی</span>
    </div>
    @if (ViewData["msg"] is not null)
    {
        <div id="viewDataMsgContainer" class="row pageMargin">
            <p class="error-text">@ViewData["msg"].ToString()</p>
        </div>
        
    }

    <div>
        @* <a href="#" id="save"><img class="img-Icon" src="~/images/diskette copy.png" /></a> *@
    </div>
    <div id="newForm" class="pageMargin">
        <form id="saveForm" asp-area="Company" asp-controller="CompanyProfile" asp-action="EditTeaser" enctype="multipart/form-data" method="post">
            <div class="form-group row">
                <div class="col-sm-2 upBtnProduct">
                    <button type="button" class="btn-submit btnUpload" onclick="getfile()">بارگذاری تیزر</button>
                    <input id="GetFile" class="notDisplay" name="teaser" type="file" accept="video/*" />
                </div>
                <div class="col-sm-2">  
                    <video class="prevImage" src="@(ViewData["src"]!=null?ViewData["src"]:"")" muted id="videoPreview" controls width="600">
                        مرورگر شما از پخش ویدیو پشتیبانی نمی‌کند.
                    </video>
                </div>
                <div class="col-sm-8">
                    @if (ViewData["src"] is not null && ViewData["src"]!=""){
                        <a href="@Url.Action("DeleteTeaser","CompanyProfile",new{area="Company"})" id="cancle"><img class="img-Icon" src="~/images/recycle.png" /></a>
                        <br />
                    }else{
                        <a href="#" onclick="DeleteVideo()" id="cancle"><img class="img-Icon" src="~/images/recycle.png" /></a>
                        <br />
                    }
                    <sapn>حداکثر حجم مجاز جهت بارگذاری فایل 20 مگابایت است.</sapn><br/>
                    <sapn>توجــــــه: فقط 5 ثانیه اول ویدیو در این بخش قابل مشاهده است.</sapn>
                </div>
            </div>
            <div>
                <div class="row mt-2">
                    <div class="col-md-5 my-2 rubyDisplay">
                        <a href="#" id="save" class="text-black btn-submit btn-block a-btn">
                            <span class="text-btn">ذخیره</span>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    <script>

        function getfile () {
            document.querySelector('#GetFile').click();
        }

        $("#save").click(function(event){
            event.preventDefault();
            $("#saveForm").submit();
        });

        function DeleteVideo(){
            $("#GetFile").val("");
            $('#videoPreview').attr('src', ''); // حذف منبع ویدئو
            $('#videoPreview')[0].load(); // بازنشانی ویدئو
        }


        $('#GetFile').on('change', function (event) {
            const videoFile = event.target.files[0]; // فایل انتخاب شده توسط کاربر
            const videoPreview = $('#videoPreview')[0]; // دریافت عنصر ویدئو
            if (videoFile) {
                const fileURL = URL.createObjectURL(videoFile); // ایجاد URL موقت از فایل
                videoPreview.src = fileURL; // تنظیم URL به عنوان منبع ویدیو
                videoPreview.load(); // بارگذاری ویدیو

                // رویداد timeupdate برای کنترل حلقه ۵ ثانیه‌ای
                $(videoPreview).on('timeupdate', function () {
                    if (videoPreview.currentTime >= 5) {
                        videoPreview.currentTime = 0; // بازگشت به ثانیه ۰
                        videoPreview.play(); // شروع دوباره پخش
                    }
                });

                videoPreview.play(); // شروع پخش خودکار
            }
        });
        setTimeout(function() {
                var msg = document.getElementById("viewDataMsgContainer");
                if (msg) {
                    msg.style.display = "none";
                }
            }, 5000);  // 5000 میلی‌ثانیه = 5 ثانیه
    </script>
}