AMPMI/WebSite.EndPoint/Areas/Company/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebSite.EndPoint.Areas.Company.Controllers
{
    [Area("Company")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AMPMI/WebSite.EndPoint/Controllers/BlogController.cs
using AQS_Application.Dtos.BaseServiceDto.BlogDtos;
using AQS_Application.Interfaces.IServices.BaseServices;
using Microsoft.AspNetCore.Mvc;
using WebSite.EndPoint.Models.Blog;

namespace WebSite.EndPoint.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        public BlogController(IBlogService blogService)
        {
            this._blogService = blogService;
        }
        public async Task<IActionResult> ShowBlog(int id)
        {
            var blog = await _blogService.ReadById(id);
            if (blog != null)
            {
                BlogDetailVM blogDetail = new BlogDetailVM()
                {
                    VideoFileName = blog.VideoFileName,
                    Id = id,
                    CreateUpdateAt = DateTime.Now,
                    Description = blog.Description,
                    HeaderPictureFileName = blog.HeaderPictureFileName,
                    Subject = blog.Subject,
                    BlogPictures = blog.BlogPictures.Select(x=>x.Route).ToList()
                };
                return View(blogDetail);
            }
            return View(new BlogDetailVM());
        }
        public async Task<IActionResult> BlogList()
        {
            var blogs = await _blogService.Read();
            List<BlogVM> blogsVM = blogs.Select(x => new BlogVM() { 
                Id = x.Id,
                Subject = x.Subject,
                CreateUpdateAt= DateTime.Now.ToPersianDate(),
                //Description = x.Description,
                HeaderPictureFileName = x.PreviousHeaderRout
            }).ToList();

            return View(blogsVM);
        }
    }
}

AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
using AQS_Application.Interfaces.IServices.BaseServices;
using Domin.Entities;
using Microsoft.AspNetCore.Mvc;
using WebSite.EndPoint.Models.CompanyViewModel;
using WebSite.EndPoint.Models.ProductViewModel;

namespace WebSite.EndPoint.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IProductService _productService;
        public CompanyController(ICompanyService companyService, IProductService productService)
        {
            _companyService = companyService;
            _productService = productService;
        }
        public async Task<IActionResult> CompanyList()
        {
            List<Company> result = await _companyService.ReadConfirmedComapanies();
            List<CompanyVM> resultVM = result.Select(x => new CompanyVM 
            {
                Id = x.Id,
                Address = x.Address,
                LogoRout = x.LogoRout,
                MobileNumber = x.MobileNumber,
                Name = x.Name,
                TeaserGuid = x.TeaserGuid,
                Email = x.Email,
                ManagerName = x.ManagerName,
                Tel = x.Tel,
                Website = x.Website,
                Partnership = x.Partnership,
                QualityGrade = x.QualityGrade,
                Iso = x.Iso,
                Capacity = x.Capacity
            }).ToList();

            return View(resultVM);
        }
        public async Task<IActionResult> CompanyDetail(long companyId)
        {
            var result = await _companyService.ReadByIdIncludePicturesAndProducts(companyId);
            if (result != null)
            {
                CompanyDetailVM companyDetailVM = new CompanyDetailVM()
                {
                    Id=companyId,
                    LogoRout = result.LogoRout,
                    Address = result.Address,
                    MobileNumber = result.MobileNumber,
                    Name = result.Name,
                    About = result.About,
                    TeaserGuid = result.TeaserGuid,
                    ManagerName= result.ManagerName,
                    CompanyPictures = result.CompanyPictures.Select(x=>x.PictureFileName).ToList(),
                    Email = result.Email,
                    Tel = result.Tel,
                    Website = result.Website,
                    Capacity = result.Capacity,
                    Iso = result.Iso,
                    Partnership = result.Partnership,
                    QualityGrade = result.QualityGrade,
                    Products = result.Products.Where(m=>m.IsConfirmed).Select(x => new ProductVM()
                    {
                        Id = x.Id,
                        Name = x.Name,
                        PictureFileName = (x.ProductPictures != null && x.ProductPictures.Count > 0) 
                        ? x.ProductPictures.FirstOrDefault().Rout 
                        : ""
                    }).ToList()
                };

                return View(companyDetailVM);
            }
            else
            {
                return View(new CompanyDetailVM());
            }
            
        }
        public async Task<IActionResult> Search(string name)
        {
            var result = await _companyService.SearchCompanyByName(name);
            var companies = result.Select(x => new CompanyVM()
            {
                Address = x.Address,
                Id = x.Id,
                Capacity = x.Capacity,
                Email = x.Email,
                Iso = x.Iso,
                LogoRout = x.LogoRout,
                MobileNumber = x.MobileNumber,
                ManagerName = x.ManagerName,    
                Name = x.Name,
                Partnership = x.Partnership,    
                QualityGrade = x.QualityGrade,
                TeaserGuid = x.TeaserGuid,
                Tel = x.Tel,
                Website = x.Website,
            }).ToList();

            return View(nameof(CompanyList), companies);
        }
        public async Task<IActionResult> SearchCompanyProduct(long companyId,string name)
        {
            var result = await _companyService.ReadByIdIncludePicture(companyId);
            var products = await _productService.SearchByProductNameAndCompanyId(name, companyId, isConfirmed: true);

            CompanyDetailVM companyDetailVM = new CompanyDetailVM()
            {
                Id = companyId,
                LogoRout = result.LogoRout,
                Address = result.Address,
                MobileNumber = result.MobileNumber,
                Name = result.Name,
                About = result.About,
                TeaserGuid = result.TeaserGuid,
                ManagerName = result.ManagerName,
                CompanyPictures = result.CompanyPictures.Select(x => x.PictureFileName).ToList(),
                Email = result.Email,
                Tel = result.Tel,
                Website = result.Website,
                Capacity = result.Capacity,
                Iso = result.Iso,
                Partnership = result.Partnership,
                QualityGrade = result.QualityGrade,
            };
            if(products!=null && products.Count > 0)
            {
                companyDetailVM.Products = products.Select(p => new ProductVM()
                {
                    Id = p.Id,
                    Name = p.Name,
                    PictureFileName = (p.ProductPictures != null && p.ProductPictures.Count > 0)
                        ? p.ProductPictures.FirstOrDefault().Rout
                        : ""
                }).ToList();
            }
            return View(nameof(CompanyDetail),companyDetailVM);
        }
    }
}

AMPMI/WebSite.EndPoint/Controllers/HomeController.cs
using AQS_Aplication.Dtos.BaseServiceDto.CategoryDto;
using AQS_Application.Dtos.BaseServiceDto.Company;
using AQS_Application.Interfaces.IServices.BaseServices;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebSite.EndPoint.Models;
using WebSite.EndPoint.Models.HomeViewModel;

namespace WebSite.EndPoint.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICategoryService _categoryService;
        private readonly ICompanyService _companyService;
        private readonly IBlogService _blogService;
        private readonly IBannerService _bannerService;

        public HomeController
            (
                ILogger<HomeController> logger,
                ICategoryService categoryService,
                ICompanyService companyService,
                IBlogService blogService,
                IBannerService bannerService
            )
        {
            _logger = logger;
            _categoryService = categoryService;
            _companyService = companyService;
            _blogService = blogService;
            _bannerService = bannerService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                HomeVM homeVM = new HomeVM();

                var categories = await _categoryService.ReadAll() ?? new List<CategoryReadDto>();
                if (categories.Count > 4)
                    categories = categories.OrderBy(x => x.Id).Take(4).ToList();
                homeVM.Categories = categories;

                var companies = await _companyService.ReadConfirmedComapanies(); ;
                homeVM.Companies = companies.Select(x => new CompanyReadDto()
                {
                    Id = x.Id,
                    Logo = x.LogoRout,
                    Name = x.Name,
                }).ToList();

                var blogs = await _blogService.ReadTop3();
                foreach (var item in blogs)
                {
                    try
                    {
                        int end = item.Description?.IndexOf("</") ?? -1;
                        int start = 0;
                        if (end > 0)
                        {
                            for (int i = end; i > 0; i--)
                            {
                                if (item.Description[i] == '>')
                                {
                                    start = i;
                                    break;
                                }
                            }
                            if (start > 10 && end > 20)
                            {
                                item.Description = item.Description.Substring(start + 1, end - start - 1);
                            }
                            else
                            {
                                item.Description = string.Empty;
                            }
                        }
                        else
                        {
                            item.Description = string.Empty;
                        }
                    }
                    catch
                    {
                        item.Description = string.Empty;
                    }
                }
                homeVM.Blogs = blogs;

                var banners = await _bannerService.ReadAll();
                homeVM.Banners = banners;
                return View(homeVM);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "خطا در بارگذاری صفحه اصلی");
                return RedirectToAction(nameof(Error));
            }
        }

        public Task<IActionResult> Error()
        {
            string StatusCode = HttpContext.Response.StatusCode.ToString();
            var errorViewModel = new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                StatusCode = StatusCode == "200" ? "404" : StatusCode   
            };

            return Task.FromResult<IActionResult>(View(errorViewModel));
        }
    }
}

AMPMI/WebSite.EndPoint/Controllers/ProductController.cs
using AQS_Application.Interfaces.IServices.BaseServices;
using Domin.Entities;
using Microsoft.AspNetCore.Mvc;
using WebSite.EndPoint.Models.ProductViewModel;

namespace WebSite.EndPoint.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;  
        public ProductController(IProductService productService,ICompanyService companyService)
        {
            this._productService = productService;
        }
        public async Task<IActionResult> ProductList()
        {
            List<Product> result = await _productService.Read();
            List<ProductVM> resultVM = result.Select(x => new ProductVM
            {
                Id = x.Id,
                Name = x.Name,
            }).ToList();

            return View(resultVM);
        }
        public async Task<IActionResult> CategoryProductsList(int categoryId)
        {
            List<Product> result = await _productService.ReadByCategoryId(categoryId, isConfirmed: true);
            List<ProductVM> resultVM = result.Select(x => new ProductVM
            {
                Id = x.Id,
                Name = x.Name,
                PictureFileName = (x.ProductPictures != null && x.ProductPictures.Count > 0) ? x.ProductPictures.FirstOrDefault().Rout : ""
            }).ToList();

            return View(nameof(ProductList), resultVM);
        }
        public async Task<IActionResult> ProductDetail(int productId) //Ok
        {
            Product? product = await _productService.ReadByIdIncludeCategoryAndSubCategoryAndCompany(productId,isConfirmed:true);
            if(product != null)
            {
                ProductDetailVM productDetailVM = new ProductDetailVM() 
                {
                    Name = product.Name,
                    Description = product.Description,
                    PictureFileName = product.ProductPictures.Select(m => m.Rout).ToList(),
                    SubCategoryId = product.SubCategoryId,
                    CompanyId = product.CompanyId ?? -1,
                    CompanyName = product.Company?.Name,
                    CompanyLogoRout = product.Company?.LogoRout,
                    CategoryId = product.SubCategory.CategoryId,
                    CategoryName = product.SubCategory.Category.Name                    
                };

                return View(productDetailVM);
            }
            else
            {
                return View(new ProductDetailVM());
            }
        }
        [HttpPost]
        public async Task<IActionResult> SearchProduct(string name, int categorySelected = -1)
        {
            if (string.IsNullOrEmpty(name))
                return View(nameof(ProductList), new List<ProductVM>());
            var result = new List<Product>();
            name = name.Trim();
            if(categorySelected > 0)
            {
                result = await _productService.SearchProductByNameAndCategory(name, categorySelected,isConfirmed:true);
            }
            else
            {
                result = await _productService.SearchProductByName(name,isConfirmed:true);
            }
            List<ProductVM> products = result.Select(x => new ProductVM() 
            {
                Id = x.Id,
                Name = x.Name,
                PictureFileName = (x.ProductPictures != null && x.ProductPictures.Count>0 ) ? x.ProductPictures.FirstOrDefault().Rout : ""
            }).ToList();

            return View(nameof(ProductList), products);
        }
    }
}

AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
@model WebSite.EndPoint.Models.HomeViewModel.HomeVM
@{
    ViewData["Title"] = "HomePage";
    ViewData["SelectedHome"] = "Home";
}


<!-- Page Loader -->
<div class="page-loader"></div>

<!-- Theme Header Start -->
<header id="home" class="full-height bg-img" data-src="/images/backgrounde.png">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <div class="header-content">
                    <div class="header-content-inner">
                        <div class="section-title">
                            <h1 class="section-title-divider animated zoomIn persianFont">انجمن قطعه‌سازان موتورسیکلت ایران</h1>
                            <h6 class="englishFont">Association of Motorcycle Parts Manufacturers in Iran</h6>
                        </div>
                        <div class="container">
                            <div class="text-right searchBar">
                                <div class="subscribe-form">
                                    <form id="search-form" method="post" asp-action="SearchProduct" asp-controller="Product" class="subscribe-form">
                                        <div class="input-group subscribe-box d-flex">
                                            <input type="text"class="form-control searchBarInput" name="name" autocomplete="off" id="mcemail"
                                            placeholder="نام موتور سیکلت، قطعه یا سازنده را جستجو نمایید ...">
                                            <div class="dropdown hide-on-sm">
                                                <button class="btn btn-default dropdown-toggle searchBarDrop" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                                   دسته‌بندی
                                                </button>
                                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                    @foreach (var item in Model.Categories)
                                                    {
                                                        <li><a class="dropdown-item" data-value="@item.Id" href="#">@item.Name</a></li>
                                                    }
                                                </ul>
                                            </div>
                                            <input hidden id="categorySelected" name="categorySelected" />
                                            <button class="btn btn-default subscribe-btn searchBarBtn" type="submit">
                                                <i class="fa fa-search" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Theme Header End -->
<!-- Service Section Start -->
<section class="padding-bottom-50" id="service">
    <div class="container text-center">
        <div class="row">
            <div class="col-sm-12">
                <div class="section-title">
                    <h4 class="section-title-divider primary-divider">دسته بندی موتور سیکلت</h4>
                </div>
            </div>
        </div>
        <div class="row service-box-wrap">
            @foreach (var item in Model.Categories)
            {
                <div class="col-md-3 col-sm-6 service-box-col">
                    <a href="@Url.Action("CategoryProductsList","Product",new {categoryId=item.Id})">
                        <figure>
                            <div class="service-image category-Pic">
                                <img class="img img-fluid category-Pic" src="@item.PictureFileName" />
                            </div>
                        </figure>
                        <h6 class="service-title title-bordered">@item.Name</h6>
                    </a>
                </div>
            }
        </div>
    </div>
</section>
<!-- Service Section End -->
<!-- Banner Section Start -->
@if (Model.Banners != null && Model.Banners.Count > 0 && Model.Banners.Any(m=>!string.IsNullOrEmpty(m.Rout))) 
{
    <section class="padding-bottom-50" id="features">
        <div class="container">
            <div class="row text-center">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h4 class="section-title-divider primary-divider">بنر</h4>
                    </div>
                </div>
            </div>
            <div class="row margin-bottom-0">
                @{
                    string cssClass = "";
                    int counter = 0;
                    foreach(var item in Model.Banners){
                        if (!string.IsNullOrEmpty(item.Rout))
                            counter++;
                    }
                    if (counter == 3)
                        cssClass = "col-md-4";
                    else if (counter == 2)
                        cssClass = "col-md-6";
                }
                @foreach (var item in Model.Banners)
                {
                    @if(!string.IsNullOrEmpty(item.Rout)){
                        <div class="@cssClass">
                            <div class="media feature-box">
                                <div class="media-left">
                                </div>
                                @if (item.Type == AQS_Domin.Entities.BannerTypeEnum.Video)
                                {
                                    <div class="media-body">
                                        <video loop autoplay class="banner" muted src="@item.Rout"></video>
                                    </div>
                                }
                                else if (item.Type == AQS_Domin.Entities.BannerTypeEnum.Image){
                                    <img class="banner" src="@item.Rout" />
                                }
                                <!-- Image is remain -->
                            </div>
                        </div>

                    }
                }            
            </div>
        </div>
    </section>

}
<!-- Banner Section End -->
<!-- Service Section Start -->
@if(Model.Companies != null && Model.Companies.Count > 0){
    <section class="padding-bottom-50" id="service2">
        <div class="container text-center">
            <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h4 class="section-title-divider primary-divider">قطعه سازان</h4>
                    </div>
                </div>
            </div>
            <div style="direction : ltr;" class="owl-carousel">
                @foreach (var item in Model.Companies)
                {
                    @if (!string.IsNullOrEmpty(item.Logo))
                    {
                        <div class="service-box-col">
                            <figure>
                                <div class="service-image category-Pic">
                                    <a href="@Url.Action("CompanyDetail","Company",new {companyId=item.Id})">
                                        <img class="img-fluid category-Pic" src="@item.Logo" />
                                    </a>
                                </div>
                                <h6 class="service-title title-bordered">@item.Name</h6>
                            </figure>
                        </div>
                    }
                }
            </div>
        </div>
    </section>

}

<!-- Service Section End -->
<!-- Blog Section Start -->
@if(Model.Blogs != null && Model.Blogs.Count > 0){
    <section class="padding-bottom-50" id="blog">
        <div class="container">
            <div class="row text-center">
                <div class="col-12">
                    <div class="section-title">
                        <h4 class="section-title-divider primary-divider">آخرین مطالب</h4>
                        <!-- SECTION TITLE -->
                        @*                     <p>
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است
                    </p> *@
                    </div>
                </div>
            </div>
            <div class="row mb-0">
                @foreach (var item in Model.Blogs)
                {
                    <div class="col-md-4">
                        <div class="blog-wrap">
                            @if (!string.IsNullOrEmpty(item.HeaderPictureFileName))
                            {
                                <div class="blog-image">
                                    <img alt="" src="@item.HeaderPictureFileName" class="img-fluid width100" />
                                </div>
                            }
                            <div class="blog-data">
                                <div class="blog-meta">
                                    <ul class="list-inline">
                                        <li>@string.Format("{0}/{1}/{2}", item.CreateUpdateAt.Value.Year, item.CreateUpdateAt.Value.Month, item.CreateUpdateAt.Value.Day)</li>
                                    </ul>
                                </div>
                                <div class="blog-title">
                                    <h3>@item.Subject</h3>
                                </div>
                                <div class="blog-content">
                                    @item.Description
                                </div>
                                <a class="btn btn-outline-secondary btn-xl mt-3" href="@Url.Action("ShowBlog","Blog",new{id=item.Id})">بیشتر بخوانید</a>
                            </div>
                        </div>
                    </div>

                }
            </div>
        </div>
    </section>

}
<!-- Blog Section End -->
@section Scripts
{
    <!-- THEME JS -->
    <script>
        var owl = $('.owl-carousel');
        owl.owlCarousel({
            items:4,
            loop:true,
            margin:10,
            autoplay:true,
            autoplayTimeout:1000,
            autoplayHoverPause:true,
            responsiveClass:true,
            responsive:{
                0:{
                    items:1,
                    nav:true
                },
                600:{
                    items:3,
                    nav:false
                },
                1000:{
                    items:4,
                    nav:true,
                    loop:true
                }
            }
        });

        $(".dropdown-item").on('click',function(){
            var selectedId = $(this).data("value");
            var selectedName = $(this).text();
            $("#dropdownMenuButton").text(selectedName);
            $("#categorySelected").val(selectedId);
        });


    </script>

}